#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $(basename $0) <iso>"
	exit 1
fi

dir=$(dirname $1)
iso=$(basename $1)
pwd=$PWD
cd $dir
sum=$(sha256sum $iso)
cd $pwd

sed -i "s/sha256.*/sha256 \`\`\`${sum}\`\`\`/" README.md
